### PR TITLE
[FEATURE] Viper initialize

### PR DESCRIPTION
**Pull request by kaedys**
- Added all of the Viper spell IDs, buff IDs, and levels.  No combos yet, though.

### CODE REVIEW

**Comment by kaedys** [comment]
May be obviated by #279 (though I like the ordering I used better =P)

**Comment by aldros-ffxi** [comment]
Oh, that var section is definitely more expansive than mine with buffs and such

**Comment by kaedys** [comment]
If you'd like to integrate it into your PR, I can close this one in favor of yours.

**Comment by MKhayle** [comment]
(I'll wait until you both agreed to something regarding this case)

**Comment by aldros-ffxi** [comment]
Ok, let me incorporate it

**Comment by aldros-ffxi** [comment]
#279 now includes your commit, I reworked mine to use your nomenclature as well

**Pull request closed without merging**
