### PR TITLE
RPR: Support for Sacrificium and Perfectio

### PR DESCRIPTION
**Pull request by lhn1703**
New Sacrificium features are an expansion to existent Lemure features under shroud after level 92.
Perfectio features are an expansion to the Communio features after level 100.

I believe this should cover most of the rest of level 91+ changes to reaper.

### CODE REVIEW

**Comment by kaedys** [comment]
Per #277, thoughts on adding a feature for Lemure's Slice/Scythe to turn into Sacrificium?  If I'm reading this PR correctly, Sacrificium will always be cast before _any_ Reaping GCDs, which means if you late weave Enshroud (or weave something before it), you are definitely going to clip the GCD.  I feel like we may need GCD detection to avoid that.  Or maybe only put Sacrificium on the GCDs if Shroud is < 5 (ie. you've used at least one of them), which should at least avoid it trying to weave Sacrificium between Enshroud and Void/Cross Reaping (it'll instead be woven between the first and second Reaping, if spammed).

**Comment by MKhayle** [comment]
RPR may need more re-tooling than just 91+ support indeed, but as I don't play the job (I'm only lvl 74) I can't test much of it and even less theorize about it. 
From what I see, the Oblatio buff didn't exist prior to 7.0 and I didn't notice it when I first released the 1.5.0.0 ; sorry. 

@kaedys' remarks about weaving are interesting though so I won't merge immediately and instead try to understand the job a bit more and either find a solution or wait for yours

**Comment by kaedys** [comment]
Ya, my thoughts were to make a feature where Lemure's Slice/Scythe turned into Sacrificium, as in the above linked issue.  That said, we do already have combos that essentially all-in-one the Enshroud sequence onto Slice (the normal combo one, not Lemure's) and Spinning Scythe, auto-selecting the Reapings and inserting Lemure's as needed, so when those are active, we should probably also have companion combos to insert Sacrificium.  However, for those we probably do need to put the above condition in and only cast it when below 5 Shroud (and prioritize Lemure's Scythe/Slice over it), so it weaves properly.

**Comment by lhn1703** [comment]
if (level >= RPR.Levels.Sacrificium && HasEffect(RPR.Buffs.Oblatio) && gauge.LemureShroud == 2)

There is a condition below 5 shroud (slice changes into sacrificium after 3rd reaping) so it will always do this sequence. Maybe you missed it in the code.
image

**Comment by kaedys** [comment]
I had missed that conditional (it got wrapped).  I'm honestly not sure about that one, tbh.  Since it ONLY weaves at 2, if the player fails to press the button during that weave window, they miss the usage entirely, since that's the last available weave window for it.  Combos haven't really ever been about perfect optimization, especially all-in-one type combos like this.  I think it'd probably make sense for the _default_ to be `<= 4` on the shroud check, so it uses it during the first weave window instead of the third, and then a sub-option to only use the third.  That makes the default more forgiving, at the cost of not being able to do the optimal opener properly (but if you're using an all-in-one, that's already at risk anyway, imo).

**Comment by kaedys** [comment]
Hmm.  I'm still concerned with people losing a usage if they don't spam the button during that third weave, or have to disconnect during it or something.  But I don't personally use the all-in-one anyway, and the 2-minute burst does use one of the two Sacrificiums in the third slot, like the opener, so I guess it's fine.  Combos are never going to be perfectly optimal anyway.

I've already got the code about half worked out for 277, so don't worry about that one.  I'll PR it once this is merged so I can rebase against it.

**Comment by kaedys** [comment]
@MKhayle This should be good to go, I think.  I'm going to suspend my objections, given that Sacrificium is used in the third weave slot quite often.  I've also got a branch ready for the changes in #277, so they don't need to be in this PR (I'm just trying to get my reaper to 92 so I can test them first).

**Pull request merged**
