### PR TITLE
[FEATURE] Miscellaneous Part 1

### LINKED ISSUE #430: [Request] DRG: Geirskogul to Wyrmwind Thrust - Prioritize Wyrmwind Thrust
Title. Right now, how the Geirskogul to Wyrmwind Thrust Feature works is that it only replaces Geirskogul when both Geirskogul and Nastrond are on cooldown. While not replacing Geirskogul makes sense, I don't see why it should wait for all three Nastrond stacks. Nastrond is a lot more lenient, giving you three OGCD stacks you can use anytime within a 20 second Geirskogul window. On the other hand, I find it far more likely a Dragoon could end up 1 GCD away from overcapping Firstmind's Focus upon entering a burst window, and need to prioritize Wyrmwind's Thrust.

### LINKED ISSUE #433: [Request] RPR: replace Soul Scythe with Guillotine
There's an <i>Expanded<i> option to put Gibbet or Gallows onto Soul Slice, but there's no option to put Guillotine on Soul Scythe. Is this something that can be done? "Soul Guillotine Feature" please and thank you.

### LINKED ISSUE #435: [Bug] Automatic Soul Slice [Reaper]
### **Reaper Melee**
It would seems that Automatic Soul Slice for Reaper works as it should if you are in a duty where it is available, alas should you enter a low level dungeon. It remains greyed out on top of the spells it replaces, meaning that to use the spells that it replaces, you would have to disable the Automatic Soul Slice. 

I have the Slice combo and Scythe combo active already so I only press 1 and 2 for my single target and my Aoe. Also have Slice Gallows Feature turned on. I was wondering if it can be fixed so that my Automatic Soul Slice does not change my spells if it is not available to be used based on the level it requires. So if I don't fullfill the level requirements for the spells, it doesn't change into them? It was a pain to figure out mid a low level dungeon why I suddenly couldn't attack because Soul Slice and Soul Scythe were replacing my spells even when the duty was lower level.

-----------------------------------------

### I am using:
•Slice Combo
•Scythe Combo
•Soul Reaver Gluttony Feature
•Automatic Soul Slice _(The issue)_
•Slice Gallows Feature
•Enshroud Communio Feature
•Arcane Harvest
•Regress Feature

-----------------------------------------

XIV Combo Expanded v2.0.0.12

-----------------------------------------

I just want Automatic Soul Slice to not replace my spells if the level requirements are not met, otherwise you have to constantly turn it off for you to be able to attack in low level duties.

If it wasn't clear, I am playing **Reaper**

### PR DESCRIPTION
**Pull request by kaedys**
- (BLM) Fixed bug with Enochian Timer feature where it could try to cast Despair even if you lack the MP to do so.
- (BLM) Removed the IsEnochianActive conditional for replacing Transpose and Umbral Soul, since it is always false before level 70.
- (BRD) Implemented feature to also put Iron Jaws on Apex Arrow for auto-refresh, and adjusted description and naming for existing auto-Iron Jaws features.
- (BRD) Implemented feature to combine Barrage with Raging Strikes.
- (BRD) Implemented inverse of existing Radiant Strikes feature, which adds Radiant Finale and Radiant Encore to Battle Voice when the latter is on CD and the former is not (helps with CD management/visibility, since Radiant Finale has 10s lower CD).
- (DNC) Fixed a bug where the automatic Saber Dance features for AoE were using the single target feature references instead.
- (DNC) Implemented feature that replaces Tillana with Saber Dance if at 50+ Esprit, to try to reduce instances of overcapping from it (SE: FFS please make Tillana grant a free usage instead of actual gauge).
- (DRG) Updated Geirskogul to Wyrmwind Thrust feature to prioritize Wyrmwind Thrust over Nastrond, since the latter has effectively no cooldown during Life of the Dragon.  The priority for usage is now Geirskogal > Wyrmwind > Nastrond.
- (MNK) Optimized Nadi functionality so it prioritizes using Lunar Nadi if Brotherhood is active (or under level), since it's higher potency.
- (MNK) Removed the ConflictingCombos setting for Coeurl Feature and Raptor Feature with Monke Mode, since the latter only affects the Opo button. NOTE: This allows users to manually perform a Solar Nadi combo if they prefer.
- (NIN) Kazematoi feature no longer conflicts with (or requires) the Aeolian Edge combo feature.
- (NIN) Implemented features for putting either Forked or Fleeting Raiju on either Aeolian Edge or Armor Crush.
- (NIN) Put a Trick Attack level check in for the Kassatsu Trick feature.
- (RPR) Fixed bug with Automatic Soul Slice/Scythe features where the replacement would occur even when under the level where those abilities are granted.
- (RPR) Implemented feature to replace Soul Scythe with Guillotine when Reaving or Enshrouded.
- (SAM) Updated and simplified Iaijutsu Tsubame Single Sen feature to simply check if Iaijutsu would be replaced by Higanbana, instead of using a direct gauge check.
- (SAM) Prioritize Shoha over Zanshin of both are available and enabled for replacing Shinten, since delaying Shoha is much more likely to result in wasted resources.
- (SGE) Moved all of the attack-related features to a "Damage" section.
- (SGE) Merged the "Rhizomata Features" and "Somethingchole Features" sections into a single "Addersgall" section.
- (VPR) Implemented feature to add ALL of the Serpent's Tail, Twinfang, and Twinblood oGCDs to the main combo buttons, to avoid overwriting them by using another oGCD (I'm *really* bad about missing the second of the two oGCDs for Uncoiled)
- (VPR) If the player has neither Honed buff, the combo buttons are left alone, rather than both being replaced with Steel Fangs/Maw.
- (VPR) The replacement of Vicewinder and Vicepit with the Twincoil Feature oGCDs now only occurs if the PvP combo for Winder/Pit is also enabled.
- Removed a number of `if (comboTime > 0)` checks, since they're strictly redundant with `lastComboMove` checks.
- Compressed a number of conditionals, and added new lines rather than depending on line wrapping in the IDE.
- Fixed a slew of lint complaints, and added some more lint ignores to the editorconfig.

Fixes #435, fixes #433, fixes #430.

### CODE REVIEW

**Comment by MKhayle** [comment]
"Part 1" 🥶

**Comment by kaedys** [comment]
Ya, I have larger sets of changes for GNB, DRK, and PCT that I decided to split into separate PRs.

**Comment by MKhayle** [comment]
I'll have time to check this out soon, sorry I've been longer than usual u_u

**Comment by MKhayle** [comment]
way longer than usual indeed

**Pull request merged**
