### PR TITLE
Add the rest of the Reign combo on EmptyBloodfestFeature

### PR DESCRIPTION
**Pull request by aldros-ffxi**
Noticed this notable absence from the EmptyBloodfestFeature, figured it'd be worth adding

### CODE REVIEW

**Comment by aldros-ffxi** [comment]
Also, man, they really changed the rotation, there's a lot less room for burst strikes anymore, the overcap feature might as well be it since you'll almost never cast it otherwise. It makes me rethink some of the other stuff like condensing stuff on burst strike.

**Comment by kaedys** [comment]
There's _more_ Burst Strikes, not less.  There just isn't _any_ room for them in the 2-minute No Mercy anymore.  But since you still get the 3 powder from Bloodfest, that means 3 extra Burst Strikes per 2 minutes that you didn't get in EW.

**Comment by aldros-ffxi** [comment]
Yeah, I seem to only use like 1 during normal rotation since I need to build stacks back up by the time No Mercy is back up

**Comment by kaedys** [comment]
So, I got curious and threw it in an Excel sheet, and I was actually a bit astonished at the results: Reign _did_ remove Burst Strikes.  Specifically, it removed 0.375 Burst Strikes per minutes.

So, background.  You get 24 GCDs per minute (at 2.5s GCD), or 48 every 2 minutes.  Each 2 minutes, you have 2 Sonic Breaks, 2 Double Downs, and 4 Gnashing Fang combos, for a total of 16 GCDs, as well as a net cartridge deficit of -5.

Now, previously, you would burn an additional 3 Burst Strikes every 2 minutes for the Bloodfest cartridges, resulting in a net cartridge deficit of -8.  8 cartridges requires 8 Solid Barrel combos, so that's 24 GCDs alone on that.  That's 43 of the 48 GCDs.  So that's one extra combo, one Burst Strike, one extra action per 2 minutes, which meant that it took 8 minutes total to make a perfect cycle.  You got 1 extra Burst Strike per 2 minutes, plus one additional every 8 minutes, for a grand total of 17 Burst Strikes per 8 minutes (12 from Bloodfest, 1 extra per 2 minutes, and 1 extra per 8 minutes), of which 13 were in No Mercy, or 2.125 Burst Strikes per minute, on average.

With Reign, you don't spend those extra 3 Burst Strikes in No Mercy, but, you still burn the same 3 GCDs per 2 minutes, it just doesn't cost cartridges because it's on the Reign combo.  Net effect is similar though, you've spent 19 of the 48 GCD, but now only have a net cartridge deficit of -5 instead of -8, which only takes 15 GCDs to offset.  So that's 34 of the 48 GCDs, leaving room for 3 full combos, 3 Burst Strikes, and 2 spare actions, meaning it only takes 4 minutes to make a perfect cycle instead of 8.  However, the way it shakes out is that you're getting 3 Burst Shots per 2 minutes, and an extra one per 4 minutes, or 14 per 8 minutes.  That's only 1.75 per minute, down from the 2.125 that it was previously.

So ya, I stand corrected, there actually _is_ less Burst Strikes per minute.  That said, previously you had 13 inside No Mercy and 4 outside it every 8 minutes.  Now you get _2_ inside No Mercy and 12 outside it.

**Comment by aldros-ffxi** [comment]
Also having tested this, I think I need to move the reign bit up a ways in the combo, since I think based on potency it should always take precedence not just when empty ammo

**Comment by MKhayle** [comment]
> Also having tested this, I think I need to move the reign bit up a ways in the combo, since I think based on potency it should always take precedence not just when empty ammo

waiting for you to do it and test it before merging in, the rest looks good to me

**Comment by kaedys** [comment]
One thing I noticed while leveling GNB recently is that the Continuation features are actually reasonably far down the list of things checked.  It's not really related to this PR, so if you'd like to punt on this, I can include it with a PR I'll be making next week instead, but I'd really like to see the Continuation check at the very top of their relevant blocks, since they are absolutely use-it-or-lose-it oGCDs.

**Comment by aldros-ffxi** [comment]
Looking it over, I think there's only one place that needs to go, but I'll add it. Other than that, PR is working as intended now

**Comment by aldros-ffxi** [comment]
Ok, did a couple more cleanups, I'll retest tomorrow to be sure

**Comment by aldros-ffxi** [comment]
So far everything seems good on it

**Pull request merged**
