### PR TITLE
[DRAFT] Remove non-working GNB combo, add new Continuation style combo

### PR DESCRIPTION
**Pull request by aldros-ffxi**
Ok, hear meow-t

I was thinking on what might make GNB more interesting, and landed on a VPR-style continuation thing for their continuation ability. It collapses a bunch of stuff onto continuation, like Burst Strike/Fated Circle, which kind of make sense to follow up their base abilities.

I marked it secret, since it does a fair amount of stuff, but wdyt?

(Also removed that Sonic Break/Bow Shock thing, since Sonic Break is now a followup to No Mercy, and that's how it works in this feature as well)

### CODE REVIEW

**Comment by aldros-ffxi** [comment]
Having just tried a dungeon with it, can confirm it feels great

**Comment by MKhayle** [comment]
the fuck is trajectory

**Comment by MKhayle** [comment]
Is there any change you'd like to add before I merge it in

**Comment by Xaenalt** [comment]
Pretty solid tbh, feels great to use

**Comment by aldros-ffxi** [comment]
Pretty solid TBH, feels great

**Pull request merged**
