### PR TITLE
BLM: Update combo presets

### PR DESCRIPTION
**Pull request by lhn1703**
First pass on new combo presets; updated between the leylines features for retrace. Did not implement aoe accessibility combo yet. 

Let me know if the icons make sense:
image
image

### CODE REVIEW

**Comment by lhn1703** [comment]
Is it possible to have buff icons like firestarter proc?

**Comment by MKhayle** [comment]
> Is it possible to have buff icons like firestarter proc?

... Technically, yes, but also, they're not the same size and they'd need to be handled differently, which is why I didn't do it. 
This may be a good further enhancement once the AttributesRework branch is merged and gone live

**Comment by kaedys** [comment]
I included a buff icon for Enhanced Harpe in the RPR one and it seemed to work perfectly fine.

**Comment by MKhayle** [comment]
hahaha no, it actually won't render fine because the nint isn't  > 60000
because I check for higher values than 60000 for rendering raw icons (UTL are all above 60000), and if they're below 60000, I fetch their skill data instead to get the icon ID

**Comment by MKhayle** [comment]
it's a bad workaround and I'll have to optimize that behavior

**Comment by MKhayle** [comment]
(technically we'll probably won't reach actions ID above 60k until 9.0 but welp)

**Comment by kaedys** [comment]
Weirdly it _did_ work, though, unless my brain has completely fallen out.  It was one of the things I specifically remember checking for, because I wasn't sure it'd work.

**Comment by kaedys** [comment]
Oh, lol.  It _does_ include an icon, but it's definitely not Enhanced Harpe's icon, it's `Plasma Field` XD

**Comment by MKhayle** [comment]
yep, that's returning the action

**Comment by MKhayle** [comment]
I'm cooking something to take care of this but also highly experimental

**Pull request merged**
