### PR TITLE
Support Reign of Beasts

### PR DESCRIPTION
**Pull request by bfabe8**
Not tested locally, but should work? Probably should be a feature support to get RoB up ahead of other things etc., but just wanted to add basic support since I just hit 100 GNB.

### CODE REVIEW

**Comment by MKhayle** [comment]
doesn't that have its own combo-ing? can't check myself rn as I'm stuck in DC travel limbos

**Comment by bfabe8** [comment]
It does - Bloodfest gets replaced by Rise of Beasts normally. However the code here previously only returned Bloodfest so it didn't combo when Bloodfest was replacing Burst Strike. I updated it to return the OriginalHook of Bloodfest, which to my understanding should replace it with whatever the game combos Bloodfest to, right?

**Comment by MKhayle** [comment]
Oh, that kind of support
I'm cooking something else before, but I'm taking notes and keeping that request open so I don't forget to think about it

**Comment by MKhayle** [comment]
OH GOD THAT'S A PULL REQUEST NOT AN ISSUE

**Comment by MKhayle** [comment]
my brain is officially fried sorry

**Pull request merged**
