### PR TITLE
Add PvP style secret combos

### PR DESCRIPTION
**Pull request by aldros-ffxi**
Alrighty, time to talk about secret combos:

This one adds a few combos:

1. Merge steel/dread fangs into 1 button like PvP (with selectable start move, otherwise weaves as expected)
2. Merge steel/dread maw into 1 button (same selectable start move as above)
3. Merge the Viper combos onto 1 button also like PvP
4. Same but for the Viper AoEs

### CODE REVIEW

**Comment by aldros-ffxi** [comment]
@kaedys some code you might be able to reuse

**Comment by masanbol** [comment]
if y'all end up needing a lv100 to test i am happy to do so again

**Comment by MKhayle** [comment]
ok so we're going for the big hammer secret combos this time
I feel WAY less guilty for this draft (my bf's request), and if someone could test it out, I'd be glad:

`CustomComboPresets.cs`
```CSharp
    [SecretCustomCombo]
    [CustomComboInfo("All-in-one Generation Legacy Feature", "Replace Generation skills with their respective Legacies.", VPR.JobID)]
    ViperAutoGenerationsLegaciesFeature = 4113,
```

`VPR.cs`
```CSharp
internal class AutoGenerationLegacies : CustomCombo
{
    protected internal override CustomComboPreset Preset { get; } = CustomComboPreset.ViperAutoGenerationsLegaciesFeature;

    protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
    {
        if (actionID == VPR.Reawaken && HasEffect(VPR.Buffs.Reawakened) && level == 100)
        {
            if (lastComboMove == VPR.Reawaken) return VPR.FirstGeneration;
            if (lastComboMove == VPR.FirstGeneration) return VPR.FirstLegacy;
            if (lastComboMove == VPR.FirstLegacy) return VPR.SecondGeneration;
            if (lastComboMove == VPR.SecondGeneration) return VPR.SecondLegacy;
            if (lastComboMove == VPR.SecondLegacy) return VPR.ThirdGeneration;
            if (lastComboMove == VPR.ThirdGeneration) return VPR.ThirdLegacy;
            if (lastComboMove == VPR.ThirdLegacy) return VPR.FourthGeneration;
            if (lastComboMove == VPR.FourthGeneration) return VPR.FourthLegacy;
            if (lastComboMove == VPR.FourthLegacy) return VPR.Ouroboros;
        }

        if (actionID == VPR.Reawaken && HasEffect(VPR.Buffs.Reawakened) && level < 100)
        {
            if (lastComboMove == VPR.Reawaken) return VPR.FirstGeneration;
            if (lastComboMove == VPR.FirstGeneration) return VPR.SecondGeneration;
            if (lastComboMove == VPR.SecondGeneration) return VPR.ThirdGeneration;
            if (lastComboMove == VPR.ThirdGeneration) return VPR.FourthGeneration;
            if (lastComboMove == VPR.FourthGeneration && level >= VPR.Levels.Ouroboros) return VPR.Ouroboros;
        }

        return actionID;
    }
}```

**Comment by MKhayle** [comment]
(I wanna test this first because iirc lastComboMove doesn't take abilities into account but I may be wrong there)

**Comment by aldros-ffxi** [comment]
You're correct, lastComboMove doesn't, but we've got a combo already that does legacies on the same buttons as their generations

**Comment by aldros-ffxi** [comment]
To adapt it for your use case, it'd be...

```
if (HasEffect(VPR.Buffs.Reawakened))
            {
                var gauge = GetJobGauge<VPRGauge>();
                var maxtribute = 4;
                if (level >= VPR.Levels.Ouroboros)
                    maxtribute = 5;
                if (gauge.AnguineTribute == maxtribute)
                    return VPR.FirstGeneration;
                if (gauge.AnguineTribute == maxtribute - 1)
                    return VPR.SecondGeneration;
                if (gauge.AnguineTribute == maxtribute - 2)
                    return VPR.ThirdGeneration;
                if (gauge.AnguineTribute == maxtribute - 3)
                    return VPR.FourthGeneration;
            }
```

**Comment by MKhayle** [comment]
yes, that's 100% reasonable
I don't even know what this anguinetribute thing is but that's useful in the current case

**Comment by aldros-ffxi** [comment]
AnguineTribute is the stacks for Generations/Ouroboros, you get a 5th stack when you get Ouroboros

**Comment by aldros-ffxi** [comment]
I haven't logged on today to test these just yet, so I'm just assuming that's how the AnguineTribute gauge works, but will have more dataz soon

**Comment by aldros-ffxi** [comment]
Ok, so far so good on testing

Only one issue I've hit is that the Dreadwinder button isn't visually replaced (but subsequent presses work as expected)

**Comment by aldros-ffxi** [comment]
Ok, that was fixed by adding an extra return and dragging a new button onto the bar, so far no issues but haven't tested legacies with this since not 100 yet

**Comment by MKhayle** [comment]
take your time 
enjoying what you're doing takes priority over this!

**Comment by aldros-ffxi** [comment]
Ngl, I am kinda really enjoying this version even though it's basically reaper with condensed buttons

**Comment by masanbol** [comment]
Testing this out - is the intent of the Winder/Pit Combo PvP buttons to not put the followup actions on the same button? They don't currently trigger off of Dreadwinder or Pit of Dread.

Also, the AoE PvP main combo doesn't seem to replace Steel Maw with Dread Maw on first use for a target without the Noxious Gash debuff. It does work if Noxious Gash is already applied.

**Comment by aldros-ffxi** [comment]
Ah, yes so in this one the followups aren't integrated, the goal here was to emulate the PvP combos

**Comment by masanbol** [comment]
Gotcha - in which case the only odd thing would be First Legacy showing up, but not sure if that's fixable. If it's not the goal to add the followups then I think it looks good

**Comment by aldros-ffxi** [comment]
Gotcha, do you have the Generation Legacy Feature enabled?

**Comment by masanbol** [comment]
I did, whoops. Looks good now. Only issue is Dread Maw not replacing Steel Maw on first use then

**Comment by aldros-ffxi** [comment]
Question on that, do you have a primary target? I wasn't able to find a way to determine if you had it on any targets other than your current

**Comment by masanbol** [comment]
Yes, it happens with a primary target selected and with no target selected. This looks like different behavior from the ST skills - Steel Fangs will always default to Dread Fangs without a target and with a target with no debuff, but the AoE skill does not.

**Comment by kaedys** [comment]
Replace this:
```
                if (level >= VPR.Levels.DreadMaw && noxious is not null && noxious?.RemainingTime < 12) // 12s hopefully means we won't miss anything on a Reawaken window
                    return VPR.DreadMaw;
                else
                    return VPR.SteelMaw;
```
With this:
```
                if (level >= VPR.Levels.DreadMaw && (noxious is null || noxious?.RemainingTime < 12)) // 12s hopefully means we won't miss anything on a Reawaken window
                    return VPR.DreadMaw;
                else
                    return VPR.SteelMaw;
```

**Comment by kaedys** [comment]
But to be honest, I actually recommend the version I used in [my commit](https://github.com/kaedys/XIVComboPlugin/commit/84a05ff4b0d2be53016ca438651f6d5fdcf3ed2e)

```
        if (actionID == VPR.DreadMaw)
        {
            if (level >= VPR.Levels.DreadMaw && IsOriginal(VPR.DreadMaw))
            {
                var gash = FindTargetEffect(VPR.Debuffs.NoxiousGash);
                if (gash is null || gash.RemainingTime <= 20)
                    return VPR.DreadMaw;

                return VPR.SteelMaw;
            }
        }
```

The time threshold is obviously adjustable to desire.  I kinda wish the combo UI had the ability to define a field input or slider to _set_ that value.

**Comment by aldros-ffxi** [comment]
Huh, weird, I do have the DreadMaw logic at https://github.com/MKhayle/XIVComboExpanded/pull/310/files#diff-4e35e7cf052570b33b233d6c45b04b5cf7c0efa41b1c8aaf84f14c26a4984eccR509-R516

It's not jumping out at me what I may have done wrong

**Comment by kaedys** [comment]
Your logic only uses Dread Maw if Noxious is non-null, ie. present on the target.  If the debuff isn't there at all, it uses Steel instead.  Hence why I recommended swapping `noxious is not null && noxious?.RemainingTime < 12` for `(noxious is null || noxious?.RemainingTime < 12)`, or if C#'s `?` operator works how I hope it does, just `noxious?.RemainingTime < 12`

**Comment by kaedys** [comment]
Note that you _are_ using `(noxious is null || noxious?.RemainingTime < 12)` for the Dread _Fangs_ conditional.

**Comment by aldros-ffxi** [comment]
Gahhh, that's it!

**Comment by aldros-ffxi** [comment]
There we go, yeah that was subtle

**Comment by kaedys** [comment]
I apparently can't tag y'all in conversations you're not already part of, so unrelated to this topic, @aldros-ffxi @masanbol could I impose on y'all to either rebase to or local build the branch in #314 and test any features you're using that depend on _cooldown or charge calculations_?  I've tested a [solid number already](https://github.com/MKhayle/XIVComboExpanded/issues/305#issuecomment-2226724616), but I'd like more eyes on this, given the size of the change and how widely used the functions I changed are.  If you encounter anything noteworthy, please lemme know on the PR or the above linked issue, so I don't derail this PR >.<.

**Comment by aldros-ffxi** [comment]
Rebased cleanly, yay

**Comment by kaedys** [comment]
Haha, I'm actually a big surprised at that, I touched nearly every file in the repo, since I changed all of `IsOnCooldown`/`IsOffCooldown`/etc function names.

**Comment by aldros-ffxi** [comment]
I only called it twice in mine, and you got those already xD

**Comment by masanbol** [comment]
I'll test local first thing tomorrow, headed to bed soon

**Comment by MKhayle** [comment]
Keep me updated about testing, as I can't do it myself! Thanks a bunch ❤️

**Comment by kaedys** [comment]
I've been running it across a number of jobs since yesterday, and it's working great for me (the CD one, not this viper PR)

**Comment by masanbol** [comment]
Apologies, I ran into an issue when building it locally with "BlackEnochianTimerFeature" not existing in CustomComboPreset and didn't have time to troubleshoot until tonight. I commented out that line and it built so I will test the Viper stuff now.

**Comment by masanbol** [comment]
Ran through everything - looks good for Viper. Issue with Dread Maw is fixed and no issues I could find with cooldowns or charges.

**Comment by MKhayle** [comment]
I'll merge this later today and use my local guinea pig to check everything

**Comment by MKhayle** [comment]
Okay, I did test them, validate them from what I did understand from the job (and the PvP version) and then proceeded to add the Combo I was personally requested in https://github.com/MKhayle/XIVComboExpanded/commit/69c85e47b68074b1cb017def0913de3f728783ea
pushing for live now!

**Comment by kaedys** [comment]
Ah, good, saved me the effort of adding that combo myself, I was just noodling on coding up exactly that today.

**Comment by MKhayle** [comment]
my boyfriend begged me for it

**Comment by kaedys** [comment]
I'm rather liking the one I have that merges the Coils down to the Fangs, which makes the Reawaken Combo 1-2-1-2 instead of 1-2-3-4.  I'm going to try to clean it up and get a PR up for it soon, I was waiting on this PR being merged before I tried, to avoid conflicts.  I might wait until I get my viper to 100, though.  Just hit 96 on it last night.

**Comment by MKhayle** [comment]
(also huge thanks @aldros-ffxi your code blocks helped me doing the reawaken all in one combo btw)

**Comment by kaedys** [comment]
Oh, side note, I'm also considering re-organizing the Viper file more similar to other files, where there's a single Invoke block per _base action_ (or sometimes, action pair, like Dread + Steel, or the Coils), rather than per _combo/feature_.  The logic of trying to avoid stepping on other combos that are touching the same ability is becoming rather complex, imo.  I think that's why Daemitus originally swapped from blocks being per combo/feature to blocks being per action (and just using the `Any` filter on the block) for most of the other jobs.

As an example, there are now two separate combo blocks that replace Hunters/Swiftskins Coil, and I have no idea which order those would apply in, or if that order is even deterministic.  There are _three_ blocks that replace Steel/Dread Fangs.  I'd rather there just be one block per base button on the bar, that checks and handles each combo needed, as that allows a very easily intuited order of priority, since it's purely defined by the order they're written in Invoke.

Thoughts?

**Comment by MKhayle** [comment]
my rule of thumb when working on a feature is:
- if multiple combos affect at least one identical action, I go for `Any`, except if all of those combos are parent/children
- if a single combo affects a single action, I go for one combo invoke for it 

the goal is to avoid invoking too many `Any` for efficiency

**Comment by kaedys** [comment]
Ya, I get it, but the Viper file has been split up by feature blocks, rather than abilities.  I figure a better way to handle it is doing it by ability (or ability pair, for closely related ones), and if that block is also confined to only a single feature atm, then it can be set for that feature, but still name is organize it per action rather than per combo.  Makes extending it easier.

**Comment by MKhayle** [comment]
Yeah, that may warrant reworking it. Getting things working was a first step, now we can optimize things and clean up it all. I'm also getting a slightly better understanding of Viper now

**Pull request merged**
