### PR TITLE
Restore the glory of the VPR PvP combos

### PR DESCRIPTION
**Pull request by aldros-ffxi**
It's back!

### CODE REVIEW

**Comment by kaedys** [comment]
Recommend rebasing this against the AttributesRework branch, and updating the combo definitions for the attribute changes.  Most likely you'll also encounter conflicts in the Viper implementation file, but hopefully not too many.

**Comment by MKhayle** [comment]
v2 is out, you can now check conflicts

**Comment by aldros-ffxi** [comment]
Luckily very few, I should be able to look into this soon(tm)

**Comment by MKhayle** [comment]
I'll need @kaedys' guidance for that one. I did grab VPR's jobstone earlier today but I am now even more lost than I was after trying to read the mountain of skills and tooltips.

**Comment by kaedys** [comment]
Ya, the Viper skill tooltips are incredibly arcane and difficult to understand.

**Comment by MKhayle** [comment]
It's just that... there's a ton, and I need to get used to both my native language's and English's spell names, status effects, in addition to the actual skill effects, and try not to mix them up.

**Comment by kaedys** [comment]
Oh ya, I'd forgotten you're also fighting the French/English translation on that front >.<.

Honestly, slapping a dummy around clarified how the job is sorta support to work for me.  The guides on Icy-Veins and on The Balance website both have good graphical flowcharts which use action and buff icons rather than (or in addition to, depending on the graphic) the action/buff names.  Highly recommend.

**Comment by MKhayle** [comment]
the thing is I'm not actually interested in understanding the job's flow in real combat/high end content, but rather how it just works at a fundamental level and then I look at how it's applied in an optimal way so that I can compare intuitive behaviour vs unintuitive/see where I was wrong in my own approach/understanding of the job
I kinda function in the reverse direction compared to yours I guess

**Comment by kaedys** [comment]
Fair.  It's definitely one of those jobs they designed to be combat-intuitive, though.  And then entirely failed to make it tooltip-intuitive.  Or tooltip-comprehensible-at-all, even _without_ dealing with translations.  Probably the single most common criticism of Viper is that the action tooltips are basically _useless_ for understanding the job.  The flowcharts cooked up by the community help far more, imo.

**Comment by aldros-ffxi** [comment]
Tbh, the entire main combo is the unintuitive part for me xD like, it seems designed for you to accidentally press the wrong button in the heat of the moment and lose 100 potency.

**Comment by kaedys** [comment]
Naw, it's not bad.  It's actually even easier with the 7.05 change.  111 222 112 221 repeat.  It's basically a simplified version of the Monk sequence, except only 2 buttons instead of 6.  And especially given that the action buttons light up for you and there's a gauge indicator to guide you (though the stock one is, imo, absolute _junk_ and basically requires mod in order to be useful.  As an example, DelvUI's version of the Vipersight gauge is literally 10x more useful than the stock one), the sequence is pretty easy to get a hold of.

What throws me is more that the second combo hit is what determines the positional.  I'm used to having my rear positionals on 2 and my flanks on 3, but Viper puts both positionals on both buttons instead.

**Pull request merged**
